### ISSUE TITLE
SSL Teacher training error

### ISSUE THREAD

**Issue by anirudh6415** [facebookresearch/GuidedDistillation#1]
**can you please help me resolve this issue** @TariqBerrada 

Traceback (most recent call last):
  File "..\GuidedDistillation\train_net.py", line 430, in <module>
    launch(
  File "\detectron2\detectron2\engine\launch.py", line 84, in the launch
    main_func(*args)
  File "\GuidedDistillation\train_net.py", line 424, in main
    return trainer.train()
  File "\GuidedDistillation\modules\defaults.py", line 570, in train
    super().train(self.start_iter, self.max_iter)
  File "\GuidedDistillation\modules\train_loop.py", line 164, in train
    self.run_step()
  File "\GuidedDistillation\modules\defaults.py", line 580, in run_step
    self._trainer.run_step()
  File "\GuidedDistillation\modules\train_loop.py", line 901, in run_step
    if self.model.module.do_ssl and self.model.module.iter % self.model.module.ssl_freq == 0 :
  File "\.conda\envs\nlp\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
**AttributeError: 'MaskFormer' object has no attribute 'module'**

**Comment by TariqBerrada** [comment]
Hello,
This is probably due to launching the job on one gpu only, which is not yet supported on the codebase.
If you try to launch the job on two or more gpus then it should not throw this error.
