### ISSUE TITLE
Train semi-supervised model using pretrained checkpoint with error.

### ISSUE THREAD

**Issue by Xinge-Zhou** [facebookresearch/GuidedDistillation#9]
I am using coco dataset and already trained the teacher model , command is `python3 -W ignore train_net.py --config-file configs/coco/instance-segmentation/maskformer2_R50_bs16_50ep.yaml --num-gpus 1 --num-machines 1 SSL.PERCENTAGE 250 SSL.TRAIN_SSL False`
When I Train semi-supervised model using pretrained checkpoint, I got error as bellow.
```
Traceback (most recent call last):
  File "/home/xiaoyao/code/GuidedDistillation/train_net.py", line 432, in <module>
    launch(
  File "/home/xiaoyao/miniconda3/envs/gd_env/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/xiaoyao/code/GuidedDistillation/train_net.py", line 426, in main
    return trainer.train()
  File "/home/xiaoyao/code/GuidedDistillation/modules/defaults.py", line 566, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/xiaoyao/code/GuidedDistillation/modules/train_loop.py", line 164, in train
    self.run_step()
  File "/home/xiaoyao/code/GuidedDistillation/modules/defaults.py", line 576, in run_step
    self._trainer.run_step()
  File "/home/xiaoyao/code/GuidedDistillation/modules/train_loop.py", line 898, in run_step
    if self.model.module.do_ssl and self.model.module.iter % self.model.module.ssl_freq == 0 :
  File "/home/xiaoyao/miniconda3/envs/gd_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MaskFormer' object has no attribute 'module'. Did you mean: 'modules'?
```

**Comment by roboyul** [comment]
See:

https://github.com/facebookresearch/GuidedDistillation/issues/1#issuecomment-1885186616

**Comment by Xinge-Zhou** [comment]
> See:
> 
> [#1 (comment)](https://github.com/facebookresearch/GuidedDistillation/issues/1#issuecomment-1885186616)

Thanks for your help, I changed the code, it can running now.

```python
"""
Update teacher model weights.
"""
if self.iter == self.model_teacher.burn_in:
    self.update_teacher_model(ema_decay=0.)
elif self.iter > self.model_teacher.burn_in:
    self.update_teacher_model(ema_decay=self.model_teacher.ema_decay)
```

**Comment by zaoruis** [comment]
> ```python
> if self.iter == self.model_teacher.burn_in:
>     self.update_teacher_model(ema_decay=0.)
> elif self.iter > self.model_teacher.burn_in:
>     self.update_teacher_model(ema_decay=self.model_teacher.ema_decay)
> ```

Hello, I try to use the code you modified, but there will still be an error, is this normal? I only used one gpu.

**Comment by zaoruis** [comment]
> > 看：
> > [#1 （评论）](https://github.com/facebookresearch/GuidedDistillation/issues/1#issuecomment-1885186616)
> 
> 感谢您的帮助，我更改了代码，它现在可以运行了。
> 
> ```python
> """
> Update teacher model weights.
> """
> if self.iter == self.model_teacher.burn_in:
>     self.update_teacher_model(ema_decay=0.)
> elif self.iter > self.model_teacher.burn_in:
>     self.update_teacher_model(ema_decay=self.model_teacher.ema_decay)
> ```

Do I need to change all model_teacher.module to model_teacher?
